/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColBtn: typeof import('./src/components/properties-drawer/atoms/cols/ColBtn.vue')['default']
    ColProperty: typeof import('./src/components/properties-drawer/atoms/cols/ColProperty.vue')['default']
    DevelopmentTable: typeof import('.storybook/components/DevelopmentTable.vue')['default']
    DraggableArea: typeof import('./src/components/builder/DraggableArea.vue')['default']
    ElementsDrawer: typeof import('./src/components/elements-drawer/ElementsDrawer.vue')['default']
    FieldWrapper: typeof import('./src/components/builder/FieldWrapper.vue')['default']
    FieldWrapperItem: typeof import('./src/components/builder/FieldWrapperItem.vue')['default']
    FieldWrapperToolbar: typeof import('./src/components/builder/FieldWrapperToolbar.vue')['default']
    FieldWrapperToolbarBtn: typeof import('./src/components/builder/FieldWrapperToolbarBtn.vue')['default']
    FieldWrapperToolbarLabel: typeof import('./src/components/builder/FieldWrapperToolbarLabel.vue')['default']
    FormBuilder: typeof import('./src/components/FormBuilder.vue')['default']
    FormNodeMock: typeof import('./src/components/builder/FormNodeMock.vue')['default']
    LoadingView: typeof import('.storybook/components/LoadingView.vue')['default']
    MainCanvas: typeof import('./src/components/main-canvas/MainCanvas.vue')['default']
    MainCanvasToolboxLeft: typeof import('./src/components/main-canvas/MainCanvasToolboxLeft.vue')['default']
    MainCanvasToolboxRight: typeof import('./src/components/main-canvas/MainCanvasToolboxRight.vue')['default']
    PropertiesDrawer: typeof import('./src/components/properties-drawer/PropertiesDrawer.vue')['default']
    PropsViewer: typeof import('./src/components/main-canvas/PropsViewer.vue')['default']
  }
}
