export type FromElementComponent =
  "text-field"
  | "duplicated-section"
  | "static-content"
  | "data-viewer"
  | 'text-area'
  | 'radio-button'
  | 'checkbox'
  | "select"
  | "location"
  | "date-picker"
  | "date-time-picker"
  | "phone"
  | "address"
  | "dictionary"
  | "combobox"
  | "button"
  | "user-input"
  | "switch"
  | "number-field"
  | "divider"
  | "image"
  | "fields-group"
  | "table-view"
  | "markdown"
